version: "3.8"

services:
  db:
    image: postgres:17.4
    container_name: scdb-postgres
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./internal/database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d # Инициализация базы данных
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: scdb-server
    restart: always
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
