CREATE TABLE IF NOT EXISTS education_organizations (
    id TEXT PRIMARY KEY,
    full_name TEXT,
    short_name TEXT,
    head_edu_org_id TEXT,
    is_branch BOOLEAN,
    post_address TEXT,
    phone TEXT,
    fax TEXT,
    email TEXT,
    web_site TEXT,
    ogrn TEXT,
    inn TEXT,
    kpp TEXT,
    head_post TEXT,
    head_name TEXT,
    form_name TEXT,
    kind_name TEXT,
    type_name TEXT,
    region_name TEXT,
    federal_district_short_name TEXT,
    federal_district_name TEXT
); 

CREATE TABLE IF NOT EXISTS cities (
    fias_id TEXT PRIMARY KEY,
    address TEXT,
    postal_code TEXT,
    country TEXT,
    federal_district TEXT,
    region_type TEXT,
    region TEXT,
    area_type TEXT,
    area TEXT,
    city_type TEXT,
    city TEXT,
    settlement_type TEXT,
    settlement TEXT,
    kladr_id TEXT,
    fias_level INTEGER,
    capital_marker INTEGER,
    okato TEXT,
    oktmo TEXT,
    tax_office TEXT,
    timezone TEXT,
    geo_lat DOUBLE PRECISION,
    geo_lon DOUBLE PRECISION,
    population INTEGER,
    foundation_year INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);


